# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20171031_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
